### PR TITLE
bump minimum php version to 7.2 to fix dependency requirements

### PR DESCRIPTION
**Pull request by mokhosh**
You can see these PRs are failing the test because the dependency requirements don't match:
https://github.com/calebporzio/sushi/pull/84
https://github.com/calebporzio/sushi/pull/85

This PR bumps the minimum php version to fix that and let the tests run on the actual code.

### CODE REVIEW

**Comment by calebporzio** [comment]
Bumping the minimum version would be a breaking change. Can you propose a different solution? What is the cause of the breakage?

**Comment by morpheus7CS** [comment]
Hey @calebporzio,

`doctrine/dbal` has to be changed to ^2.9 instead of ^2.10, if you would like to support the PHP 7.1 version.
For more informaion, check the PR #83.

Kind regards,
g

**Comment by mokhosh** [comment]
I don't know if downgrading `dbal` would have any issues but that seems to be the other solution:
```
Error: Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.2|^8.0 but your php version (7.1.33) does not satisfy that requirement.
  Problem 2
    - doctrine/dbal[2.12.0, ..., 2.12.x-dev] require php ^7.3 || ^8 -> your php version (7.1.33) does not satisfy that requirement.
    - doctrine/dbal[v2.10.0, ..., 2.10.4] require php ^7.2 -> your php version (7.1.33) does not satisfy that requirement.
    - doctrine/dbal[2.11.0, ..., 2.11.3] require php ^7.3 -> your php version (7.1.33) does not satisfy that requirement.
    - Root composer.json requires doctrine/dbal ^2.10 -> satisfiable by doctrine/dbal[v2.10.0, ..., 2.12.x-dev].


  Problem 1
    - Root composer.json requires php ^7.2|^8.0 but your php version (7.1.33) does not satisfy that requirement.
  Problem 2
    - doctrine/dbal[2.12.0, ..., 2.12.x-dev] require php ^7.3 || ^8 -> your php version (7.1.33) does not satisfy that requirement.
    - doctrine/dbal[v2.10.0, ..., 2.10.4] require php ^7.2 -> your php version (7.1.33) does not satisfy that requirement.
    - doctrine/dbal[2.11.0, ..., 2.11.3] require php ^7.3 -> your php version (7.1.33) does not satisfy that requirement.
    - Root composer.json requires doctrine/dbal ^2.10 -> satisfiable by doctrine/dbal[v2.10.0, ..., 2.12.x-dev].
```

**Comment by calebporzio** [comment]
I merged in @morpheus7CS's PR so this one shouldn't be needed anymore. Thanks!

**Pull request closed without merging**
