### PR TITLE
Fix checking and adding primary key

### PR DESCRIPTION
**Pull request by shadoWalker89**
EDIT: 
I rebased this PR branch onto the master branch and i noticed that it was fixed but slightly different. But i think doing a `array_key_exists` is easier to read also my PR has tests to verify that adding an auto increment primary key is working as intended.

------------------------

Original message :

Sushi checks if the definition of the primary key exists in the rows, if not it tries to automatically add it.
Checking this condition is wrong, this PR fixes that.

Before the PR if you do something like this

```php
class FooWithKey extends Model
{
    use \Sushi\Sushi;

    protected $rows = [
        ['id' => 5, 'foo' => 'bar', 'bob' => 'lob'],
        ['id' => 6, 'foo' => 'baz', 'bob' => 'law'],
    ];
}
```

You will get an error (defining the primary key column twice) when trying to migrate the table.

`Illuminate\Database\QueryException : SQLSTATE[HY000]: General error: 1 duplicate column name: id (SQL: create table "foo_with_keys" ("id" integer not null primary key autoincrement, "id" integer not null primary key autoincrement, "foo" varchar not null, "bob" varchar not null))`

### CODE REVIEW

**Comment by ce-brex** [comment]
Such a face palm moment on my part...

**Comment by shadoWalker89** [comment]
The failing tests are due to the tests being skipped and added in this PR https://github.com/calebporzio/sushi/pull/31

**Comment by calebporzio** [comment]
Dig it, thanks!

**Comment by calebporzio** [comment]
Ooops mind getting this PR up to date with master? Will merge after. Thanks!

**Pull request merged**
