### PR TITLE
Feature: Allow Sushi to work even when there is no data available.

### PR DESCRIPTION
**Pull request by Sammyjo20**
Hi Caleb 👋

Thank you for Sushi, I really love using it. 

I recently ran into a scenario where I was using `getRows()` to grab data from a third party API, but sometimes the API would return an empty array as its results. Looking into the Sushi trait, it looks like it depends on at least one row of data to be within the array, because it uses that row to work out the column structure. 

To get around this, I wrote two new methods that are invoked on the `migrate()` method. One is `createTable` and the other is `createTableWithNoData`. If there happens to be no rows available, this will look for a new `protected $columns` where you can define your own table structure, all within the model! I've used the same data types that you had in your original `migrate()` command to ensure compatibility.

I also built a simple test for this too, but I'd love to know your thoughts.

### CODE REVIEW

**Comment by danharrin** [comment]
Hey Sam! Hope you don't mind me jumping in... how about hijacking the existing `$schema` array? I do the same with my fork of Sushi for Squire v2 :)

https://github.com/squirephp/squire/blob/main/packages/model/src/Model.php#L124-L126

**Comment by Sammyjo20** [comment]
Hey Dan, thanks for your comment - great idea! I'll update that now 😊

**Comment by calebporzio** [comment]
@danharrin are you interested in PRing your update to Sushi core?

**Comment by Sammyjo20** [comment]
@calebporzio I updated this PR with Dan's schema logic. Do we need a `getSchema()` method?

**Comment by danharrin** [comment]
I need this functionality and this is a really neat implementation, +1 for merging.

**Comment by Sammyjo20** [comment]
@calebporzio This PR had some merge conflicts which I have now resolved.

**Comment by tim-bec** [comment]
@calebporzio would be great to see this feature in the sushi core. We also experience problems with getRow() and empty api respones.

**Comment by calebporzio** [comment]
Great, thanks for the nudge. I agree 👌

**Comment by Sammyjo20** [comment]
Thanks for merging @calebporzio 🤘

**Comment by tim-bec** [comment]
@calebporzio  Would it be possible to create a release for composer? <3

**Comment by calebporzio** [comment]
Done, tagged: v2.2.0

**Pull request merged**
